;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
		TeX-insert-backslash
		c-electric-delete-forward
		c-electric-paren
		c-indent-line-or-region
		electric-newline-and-maybe-indent
		org-delete-char
		org-self-insert-command
		org-yank
		save-some-buffers
		sh-assignment
		))

(setq mc/cmds-to-run-once
      '(
		))
