;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
		electric-newline-and-maybe-indent
		org-delete-char
		org-self-insert-command
		save-some-buffers
		sh-assignment
		))

(setq mc/cmds-to-run-once
      '(
		))
